<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalServerSdkLib\Models\BLIKLevel0PaymentObject;

/**
 * Builder for model BLIKLevel0PaymentObject
 *
 * @see BLIKLevel0PaymentObject
 */
class BLIKLevel0PaymentObjectBuilder
{
    /**
     * @var BLIKLevel0PaymentObject
     */
    private $instance;

    private function __construct(BLIKLevel0PaymentObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new bliklevel 0 payment object Builder object.
     */
    public static function init(string $authCode): self
    {
        return new self(new BLIKLevel0PaymentObject($authCode));
    }

    /**
     * Initializes a new bliklevel 0 payment object object.
     */
    public function build(): BLIKLevel0PaymentObject
    {
        return CoreHelper::clone($this->instance);
    }
}
