<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\BLIKOneClickPaymentRequest;

/**
 * Builder for model BLIKOneClickPaymentRequest
 *
 * @see BLIKOneClickPaymentRequest
 */
class BLIKOneClickPaymentRequestBuilder
{
    /**
     * @var BLIKOneClickPaymentRequest
     */
    private $instance;

    private function __construct(BLIKOneClickPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new blikone click payment request Builder object.
     */
    public static function init(string $consumerReference): self
    {
        return new self(new BLIKOneClickPaymentRequest($consumerReference));
    }

    /**
     * Sets auth code field.
     */
    public function authCode(?string $value): self
    {
        $this->instance->setAuthCode($value);
        return $this;
    }

    /**
     * Sets alias label field.
     */
    public function aliasLabel(?string $value): self
    {
        $this->instance->setAliasLabel($value);
        return $this;
    }

    /**
     * Sets alias key field.
     */
    public function aliasKey(?string $value): self
    {
        $this->instance->setAliasKey($value);
        return $this;
    }

    /**
     * Initializes a new blikone click payment request object.
     */
    public function build(): BLIKOneClickPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
