<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalServerSdkLib\Models\CycleFrequency;

/**
 * Builder for model CycleFrequency
 *
 * @see CycleFrequency
 */
class CycleFrequencyBuilder
{
    /**
     * @var CycleFrequency
     */
    private $instance;

    private function __construct(CycleFrequency $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cycle Frequency Builder object.
     *
     * @param string $intervalUnit
     */
    public static function init(string $intervalUnit): self
    {
        return new self(new CycleFrequency($intervalUnit));
    }

    /**
     * Sets interval count field.
     *
     * @param int|null $value
     */
    public function intervalCount(?int $value): self
    {
        $this->instance->setIntervalCount($value);
        return $this;
    }

    /**
     * Initializes a new Cycle Frequency object.
     */
    public function build(): CycleFrequency
    {
        return CoreHelper::clone($this->instance);
    }
}
