<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalServerSdkLib\Models\VenmoWalletCustomerInformation;

/**
 * Builder for model VenmoWalletCustomerInformation
 *
 * @see VenmoWalletCustomerInformation
 */
class VenmoWalletCustomerInformationBuilder
{
    /**
     * @var VenmoWalletCustomerInformation
     */
    private $instance;

    private function __construct(VenmoWalletCustomerInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Venmo Wallet Customer Information Builder object.
     */
    public static function init(): self
    {
        return new self(new VenmoWalletCustomerInformation());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets email address field.
     *
     * @param string|null $value
     */
    public function emailAddress(?string $value): self
    {
        $this->instance->setEmailAddress($value);
        return $this;
    }

    /**
     * Initializes a new Venmo Wallet Customer Information object.
     */
    public function build(): VenmoWalletCustomerInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
