<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\VenmoWalletExperienceContext;

/**
 * Builder for model VenmoWalletExperienceContext
 *
 * @see VenmoWalletExperienceContext
 */
class VenmoWalletExperienceContextBuilder
{
    /**
     * @var VenmoWalletExperienceContext
     */
    private $instance;

    private function __construct(VenmoWalletExperienceContext $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new venmo wallet experience context Builder object.
     */
    public static function init(): self
    {
        return new self(new VenmoWalletExperienceContext());
    }

    /**
     * Sets brand name field.
     */
    public function brandName(?string $value): self
    {
        $this->instance->setBrandName($value);
        return $this;
    }

    /**
     * Sets shipping preference field.
     */
    public function shippingPreference(?string $value): self
    {
        $this->instance->setShippingPreference($value);
        return $this;
    }

    /**
     * Initializes a new venmo wallet experience context object.
     */
    public function build(): VenmoWalletExperienceContext
    {
        return CoreHelper::clone($this->instance);
    }
}
