<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models;

use PaypalServerSdkLib\ApiHelper;
use stdClass;

/**
 * The frequency of the terms reset cycle.
 */
class CycleFrequency implements \JsonSerializable
{
    /**
     * @var string
     */
    private $intervalUnit;

    /**
     * @var int|null
     */
    private $intervalCount = 1;

    /**
     * @param string $intervalUnit
     */
    public function __construct(string $intervalUnit)
    {
        $this->intervalUnit = $intervalUnit;
    }

    /**
     * Returns Interval Unit.
     * The interval unit at which the the usage limits will be reset.
     */
    public function getIntervalUnit(): string
    {
        return $this->intervalUnit;
    }

    /**
     * Sets Interval Unit.
     * The interval unit at which the the usage limits will be reset.
     *
     * @required
     * @maps interval_unit
     */
    public function setIntervalUnit(string $intervalUnit): void
    {
        $this->intervalUnit = $intervalUnit;
    }

    /**
     * Returns Interval Count.
     * The interval count at which the terms will be reset, this is ignored if the unit is LIFETIME.
     */
    public function getIntervalCount(): ?int
    {
        return $this->intervalCount;
    }

    /**
     * Sets Interval Count.
     * The interval count at which the terms will be reset, this is ignored if the unit is LIFETIME.
     *
     * @maps interval_count
     */
    public function setIntervalCount(?int $intervalCount): void
    {
        $this->intervalCount = $intervalCount;
    }

    /**
     * Converts the CycleFrequency object to a human-readable string representation.
     *
     * @return string The string representation of the CycleFrequency object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CycleFrequency',
            ['intervalUnit' => $this->intervalUnit, 'intervalCount' => $this->intervalCount]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['interval_unit']      = $this->intervalUnit;
        if (isset($this->intervalCount)) {
            $json['interval_count'] = $this->intervalCount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
