<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models;

/**
 * The interval unit at which the the usage limits will be reset.
 */
class FrequencyIntervalUnit
{
    /**
     * A daily cycle.
     */
    public const DAY = 'DAY';

    /**
     * A weekly cycle.
     */
    public const WEEK = 'WEEK';

    /**
     * A monthly cycle.
     */
    public const MONTH = 'MONTH';

    /**
     * A yearly cycle.
     */
    public const YEAR = 'YEAR';

    /**
     * The lifetime of the BA translates to 1 cycle
     */
    public const LIFETIME = 'LIFETIME';
}
