<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models;

/**
 * The HTTP method required to make the related call.
 */
class LinkHttpMethod
{
    public const GET = 'GET';

    public const POST = 'POST';

    public const PUT = 'PUT';

    public const DELETE = 'DELETE';

    public const HEAD = 'HEAD';

    public const CONNECT = 'CONNECT';

    public const OPTIONS = 'OPTIONS';

    public const PATCH = 'PATCH';
}
