<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models;

/**
 * The phone type.
 */
class PhoneType
{
    public const FAX = 'FAX';

    public const HOME = 'HOME';

    public const MOBILE = 'MOBILE';

    public const OTHER = 'OTHER';

    public const PAGER = 'PAGER';
}
