<?php

declare(strict_types=1);

/*
 * PaypalServerSdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSdkLib\Models;

/**
 * The status of the subscription.
 */
class SubscriptionStatus
{
    /**
     * The subscription is created but not yet approved by the buyer.
     */
    public const APPROVAL_PENDING = 'APPROVAL_PENDING';

    /**
     * The buyer has approved the subscription.
     */
    public const APPROVED = 'APPROVED';

    /**
     * The subscription is active.
     */
    public const ACTIVE = 'ACTIVE';

    /**
     * The subscription is suspended.
     */
    public const SUSPENDED = 'SUSPENDED';

    /**
     * The subscription is cancelled.
     */
    public const CANCELLED = 'CANCELLED';

    /**
     * The subscription is expired.
     */
    public const EXPIRED = 'EXPIRED';
}
