<?php

declare(strict_types=1);

/*
 * PaypalServerSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalServerSDKLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const DEFAULT_ = 'default';
}
